name = "NNG4"
description = "Natural Number Game"
license = "Apache-2.0"
licenseFiles = ["LICENSE"]

defaultTargets = ["Game"]

[leanOptions]
# linter warnings might block the player. (IMPORTANT)
linter.all = false
# make all assumptions always accessible.
tactic.hygienic = false

[moreServerOptions]
# TODO: replace with `lean4game.verbose`
trace.debug = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "73ff1bf4b25fb7ed4b2413eed2f991aa0794dc3f"

[[require]]
name = "I18n"
scope = "hhu-adam"
rev = "main"

[[require]]
name = "GameServer"
scope = "leanprover-community"
source = { type = "git", url = "https://github.com/leanprover-community/lean4game", subDir = "server", rev = "master" }


[[lean_lib]]
name = "Game"
# TODO: replace with `lean4game.verbose`
moreLeanArgs = ["-Dtrace.debug=false"]
